<?php

$this->headTitle('Add Task');

$this->mainMenu()->setActiveItemId('projects');

$this->pageBreadcrumbs()->setItems([
    'Home'=>$this->url('home'),
    'Manage Projects'=>$this->url('tasks'),
    'Add Project'=>$this->url('tasks', ['action'=>'add'])
]);

$form->get('task_title')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Title'
]);

$form->get('description')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Description'
]);

$form->get('status')->setAttributes([
    'class'=>'form-control'
]);

$form->get('project_id')->setAttributes([
    'value' => $projectId,
    'id' => 'project_id'
]);

$form->get('estimate')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Task estimate',
    'id' => 'estimate',
]);
$form->get('estimate_hours')->setAttributes([
    'class' => 'form-control',
    'id' => 'estimate_hours',
    'placeholder' => 'Hours',
]);
$form->get('estimate_minutes')->setAttributes([
    'class' => 'form-control',
    'id' => 'estimate_minutes',
    'placeholder' => 'Minutes',
]);

$form->get('priority')->setAttributes([
    'id' => 'priority',
    'class'=>'form-control',
    'placeholder'=>'Priority'
]);

$form->get('assigned_user_id')->setAttributes([
    'id' => 'assigned-user-id',
    'class' => 'form-control',
    'placeholder' => 'Assigned user'
]);


$form->get('submit')->setAttributes(['class'=>'btn btn-primary', 'onclick' => 'prepareSubmit();']);

$form->prepare();
?>

<h1>Add Task</h1>

<p>
    Please fill out the following form and click the <i>Create</i> button.
</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>
        
        <?= $this->formElement($form->get('project_id')); ?>
<!--        <input type="hidden" name="project_id" value="--><?//= $projectId; ?><!--">-->

        <div class="form-group">
            <?= $this->formLabel($form->get('task_title')); ?>
            <?= $this->formElement($form->get('task_title')); ?>
            <?= $this->formElementErrors($form->get('task_title')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('description')); ?>
            <?= $this->formElement($form->get('description')); ?>
            <?= $this->formElementErrors($form->get('description')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('status')); ?>
            <?= $this->formElement($form->get('status')); ?>
            <?= $this->formElementErrors($form->get('status')); ?>
        </div>

        <div class="form-group">
            <div class="estimates-block">
                <label for="" style="text-align: center; display: block;">Estimate</label>
                <?= $this->formLabel($form->get('estimate_hours')); ?>
                <?= $this->formElement($form->get('estimate_hours')); ?>
                <?= $this->formElementErrors($form->get('estimate_hours')); ?>

                <?= $this->formLabel($form->get('estimate_minutes')); ?>
                <?= $this->formElement($form->get('estimate_minutes')); ?>
                <?= $this->formElementErrors($form->get('estimate_minutes')); ?>
            </div>
        </div>


        <div class="form-group">
            <?= $this->formLabel($form->get('priority')); ?>
            <?= $this->formElement($form->get('priority')); ?>
            <?= $this->formElementErrors($form->get('priority')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('assigned_user_id')); ?>
            <?= $this->formElement($form->get('assigned_user_id')); ?>
            <?= $this->formElementErrors($form->get('assigned_user_id')); ?>
        </div>

        <div class="choose-user-wrapper">
            <div class="form-group">
                <div class="result-block" id="result-block"></div>
                <label for="">Choose user type and press button:</label>
                <div class="clearer"></div>
                <?php foreach ($roles as $role): ?>
                    <input type="radio" name="user_type" value="<?= $role->getId(); ?>" id="choose-<?= $role->getId(); ?>">
                    <label for="choose-<?= $role->getId(); ?>"><?= $role->getName(); ?></label>
                    <div class="clearer"></div>
                <?php endforeach; ?>
            </div>

            <button type="button" class="btn btn-default" onclick="chooseUserAutomatically(<?= $projectId; ?>, true); return false;">
                <span class="glyphicon glyphicon-retweet"></span>
                Choose automatically
            </button>

        </div>

        <?= $this->formElement($form->get('submit')); ?>
        
        <?= $this->form()->closeTag(); ?>
    </div>    
</div>

<script type="text/javascript">

    window.onload = function() {
        $("#project-form" ).validate({
            rules: {
                estimate_hours: {
                    required: false,
                    number: true
                },
                estimate_minutes: {
                    required: false,
                    number: true
                },
            }
        });
    };

    function prepareSubmit() {
        var estimate_time_hours = $('#estimate_hours').val();
        var estimate_time_minutes = $('#estimate_minutes').val();

        if (!$('#project-form').valid()){
            alert('Not valid value for estimate time');
            return false;
        }

        var totalEstimateMinutes = (Number(estimate_time_hours) * 60) + Number(estimate_time_minutes);
        if (!$.isNumeric(totalEstimateMinutes)) {
            alert('Not valid value for estimate time');
            return false;
        }
        $('#estimate').val(totalEstimateMinutes);
        return true;
    }
</script>
