<?php
$this->headTitle('Tasks');

$this->mainMenu()->setActiveItemId('tasks');

$this->pageBreadcrumbs()->setItems([
    'Home'=>$this->url('home'),
    'Manage Tasks'=>$this->url('tasks'),
]);
?>

<h1>Assigned Tasks</h1>

<table class="table table-striped">

    <tr>
        <th>ID</th>
        <th>Title</th>
        <th>Status</th>
        <th>Description</th>
        <th>Date Created</th>
        <th>Actions</th>
    </tr>

    <?php foreach ($tasks as $task): ?>
        <?php $project = $task->getProject(); ?>

        <tr>
            <td><?= $this->escapeHtml($task->getId()); ?></td>
            <td><?= $this->escapeHtml($task->getTaskTitle()); ?></td>
            <td><strong><?= $this->escapeHtml($taskManager->getStatusAsString($task->getStatus())); ?></strong></td>
            <td><?= $this->escapeHtml($task->getDescription()); ?></td>
            <td><?= $this->escapeHtml($task->getDateCreated()); ?></td>
            <td>
                <a class="btn btn-info" href="<?= $this->url('tasks',
                    ['action'=>'edit', 'task' => $task->getId(), 'project' => $project->getCode()]); ?>">
                    <span class="glyphicon glyphicon-pencil" ></span> Edit
                </a>
                <a class="btn btn-info" href="<?= $this->url('tasks',
                    ['action'=>'view', 'task' => $task->getId(), 'project' => $project->getCode()]); ?>">
                    <span class="glyphicon glyphicon-pencil" ></span> View
                </a>
                <?php if ($this->access('projects.manage.all') ||
                        $this->access('projects.manage.own', ['project' => $project])): ?>
                    <a class="btn btn-danger" href="<?= $this->url('tasks',
                        ['action' => 'delete', 'project' => $project->getCode(), 'task' => $task->getId()]); ?>">
                        <span class="glyphicon glyphicon-remove"></span> Delete
                    </a>
                <?php endif; ?>
            </td>
        </tr>

    <?php endforeach; ?>

</table>

