<?php
$this->headTitle('Tasks');

$this->mainMenu()->setActiveItemId('tasks');

$this->pageBreadcrumbs()->setItems([
    'Home'=>$this->url('home'),
    'Manage Tasks'=>$this->url('tasks'),
]);
?>

<h1>Assigned Tasks</h1>
<div class="form-group">
    <label for="status_filter">Status Filter</label>
    <select name="status_filter" id="status_filter" class="form-control">
        <option value="0" <?php echo ($currentFilterStatus == 0)? 'selected="selected"':'';?> >All</option>
        <?php foreach ($allStatuses as $status): ?>
            <option value="<?= $status->getId(); ?>" <?php echo ($currentFilterStatus == $status->getId())? 'selected="selected"':'';?> ><?= $status->getLabel(); ?></option>
        <?php endforeach; ?>
    </select>
</div>
<script type="text/javascript">
    $("#status_filter" ).change(function(element) {
        console.log($(this));
        console.log($(this).val());
        var selectedStatus = $(this).val();
        var generalUrl = '<?= $this->url('tasks', ['action'=>'index']); ?>';
        window.location = generalUrl + '?filter_status='+selectedStatus
    });
</script>

<table class="table table-striped">

    <tr>
        <th>ID</th>
        <th>Title</th>
        <th>Status</th>
        <th>Description</th>
        <th>Date Created</th>
        <th>Actions</th>
    </tr>

    <?php foreach ($tasks as $task): ?>
        <?php $project = $task->getProject(); ?>

        <tr>
            <td><?= $this->escapeHtml($task->getId()); ?></td>
            <td><?= $this->escapeHtml($task->getTaskTitle()); ?></td>
            <td><strong><?= $this->escapeHtml($taskManager->getStatusAsString($task->getStatus())); ?></strong></td>
            <td><?= $this->escapeHtml($task->getDescription()); ?></td>
            <td><?= $this->escapeHtml($task->getDateCreated()); ?></td>
            <td>
                <a class="btn btn-info" href="<?= $this->url('tasks',
                    ['action'=>'edit', 'task' => $task->getId(), 'project' => $project->getCode()]); ?>">
                    <span class="glyphicon glyphicon-pencil" ></span> Edit
                </a>
                <a class="btn btn-info" href="<?= $this->url('tasks',
                    ['action'=>'view', 'task' => $task->getId(), 'project' => $project->getCode()]); ?>">
                    <span class="glyphicon glyphicon-pencil" ></span> View
                </a>
                <?php if ($this->access('projects.manage.all') ||
                        $this->access('projects.manage.own', ['project' => $project])): ?>
                    <a class="btn btn-danger" href="<?= $this->url('tasks',
                        ['action' => 'delete', 'project' => $project->getCode(), 'task' => $task->getId()]); ?>">
                        <span class="glyphicon glyphicon-remove"></span> Delete
                    </a>
                <?php endif; ?>
            </td>
        </tr>

    <?php endforeach; ?>

</table>

