<?php $user = $timeLog->getUser(); ?>
<div class="time-log-block" id="time-log-block-<?= $timeLog->getId(); ?>">
    <div class="time-log-header">
        <span class="time-log-user-name"><strong><?= $user->getFullName(); ?></strong></span>

        <span class="time-log-label">spent</span>
        <span class="time-log-time" id="time-log-time-<?= $timeLog->getId(); ?>"><?= $this->projectHelper()->formatTime($timeLog->getSpentTime()); ?></span>

        <span class="time-log-label">on</span>
        <span class="time-log-date"><?= date('d F Y', strtotime($timeLog->getDateCreated())); ?></span>

        <span class="edit-time-log-button" id="edit-time-log-button-<?= $timeLog->getId(); ?>"
              onclick="editTimeLog(<?php echo $timeLog->getId(); ?>); return false;"><a href="#"
                                                                                        class="btn btn-default"><span
                    class="glyphicon glyphicon-pencil"></span></a></span>

        <div class="clearer"></div>

        <div class="buttons-wrapper">
            <button onclick="editTimeLogPost(<?= $timeLog->getId(); ?>)" id="time-log-save-button-<?= $timeLog->getId(); ?>"
                    class="time-log-save-button btn btn-default" type="button"><span class="glyphicon glyphicon-ok"></span> Save
            </button>

            <span class="cancel-time-log-edit-button" id="cancel-time-log-edit-button-<?= $timeLog->getId(); ?>" onclick="cancelEditTimeLog(<?php echo $timeLog->getId(); ?>); return false;"><a href="#" class="btn btn-default"><span class="	glyphicon glyphicon-remove"></span></a></span>
        </div>
    </div>
    <form action="#" class="time-log-edit-form" id="time-log-form-edit-<?= $timeLog->getId(); ?>">
        <label for="spent_time_hours_edit_<?= $timeLog->getId(); ?>">H</label>
        <input class="time-log-edit-input form-control" name="spent_time_hours_edit_<?= $timeLog->getId(); ?>" id="spent_time_hours_edit_<?= $timeLog->getId(); ?>"
            value="<?= $this->projectHelper()->formatTime($timeLog->getSpentTime(), 'h'); ?>">
        <label for="spent_time_minutes_edit_<?= $timeLog->getId(); ?>">M</label>
        <input class="time-log-edit-input form-control" name="spent_time_minutes_edit_<?= $timeLog->getId(); ?>" id="spent_time_minutes_edit_<?= $timeLog->getId(); ?>"
               value="<?= $this->projectHelper()->formatTime($timeLog->getSpentTime(), 'm'); ?>">
    </form>
    <div class="clearer"></div>

    <script type="text/javascript">
        jQuery.validator.setDefaults({
            debug: true,
            success: "valid"
        });
        $("#time-log-form-edit-<?= $timeLog->getId(); ?>").validate({
            rules: {
                spent_time_hours_edit_<?= $timeLog->getId(); ?>: {
                    required: false,
                    number: true
                },
                spent_time_minutes_edit_<?= $timeLog->getId(); ?>: {
                    required: false,
                    number: true
                },
            }
        });
    </script>
</div>