<?php
$this->headTitle('View Task');

$this->mainMenu()->setActiveItemId('tasks');

$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Manage Tasks' => $this->url('tasks'),
    'View Task' => $this->url('tasks', ['action' => 'view', 'id' => $task->getId()])
]);
?>

<? if($project): ?>
    <h2>Project:</h2>
    <?= $project->getName();?>
<? endif; ?>


<h1>View Task</h1>
<a href="<?php echo $this->url('tasks', ['action' => 'edit', 'id' => $task->getId()]); ?>">Edit</a>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
            <tr>
                <th>ID:</th>
                <td>
                <?= $this->escapeHtml($task->getId()) ?></th>
            </tr>
            <tr>
                <th>Title:</th>
                <td>
                <?= $this->escapeHtml($task->getTaskTitle()) ?></th>
            </tr>
            <tr>
                <th>Description:</th>
                <td>
                <?= $this->escapeHtml($task->getDescription()) ?></th>
            </tr>
            <tr>
                <th>Estimate:</th>
                <td>
                <?= $this->escapeHtml($task->getEstimate()) ?></th>
            </tr>
            <tr>
                <th>Date Created:</th>
                <td>
                <?= $this->escapeHtml($task->getDateCreated()) ?></th>
            </tr>
            <tr>
                <th>Status:</th>
                <td>
                <?= $this->escapeHtml($status) ?></th>
            </tr>
            <tr>
                <th>Priority:</th>
                <td>
                <?= $this->escapeHtml($task->getPriority()) ?></th>
            </tr>
            <tr>
                <th>Assigned user:</th>
                <td>
                <?= $this->escapeHtml($task->getAssignedUser()->getFullName()) ?></th>
            </tr>
        </table>
    </div>
</div>

<? if($comments): ?>
    <div class="comments-wrapper" id="comments-wrapper">
        <div class="comments-title"><strong>Comments</strong></div>
        <?php foreach ($comments as $comment): ?>
            <?= $this->partial('comment.phtml', array('comment' => $comment)); ?>
        <?php endforeach; ?>
    </div>
<? endif; ?>

<div class="add-comment-block">
<!--    --><?//= $commentForm; ?>
    <?= $this->formElement($commentForm->get('comment_text')); ?>
    <?= $this->formElement($commentForm->get('submit')); ?>
</div>

<script type="text/javascript">
    function addComment(){
        var data = {};
        data.comment_text = $('#comment-text').val();
        $.ajax({
            type:'POST',
            dataType: 'json',
            url:'/comments/add/<?php echo $task->getId(); ?>',
            data: data,
            success: function(data){
                console.log(data);
                if(data.response) {
                    addMessage(data.message, 'success')
                }else{
                    addMessage(data.message, 'error')
                }
                if(data.comment_html){
                    $(".comments-wrapper").append(data.comment_html);
                }
            }
        });
    }
</script>
