<?php
$this->headTitle('View Task');

$this->mainMenu()->setActiveItemId('tasks');

$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    $project->getName() => $this->url('projects', ['action' => 'view', 'code' => $project->getCode()]),
    'View Task' => $this->url('tasks', ['action' => 'view', 'task' => $task->getId(), 'project' => $project->getCode()])
]);
$estimate = $task->getEstimate();
?>

<div class="col-md-9">

<? if($project): ?>
    <h4><a href="<?= $this->url('projects', ['action' => 'view', 'code' => $project->getCode()]);?>"><?= $project->getName();?></a></h4>
<? endif; ?>


<h3><?= $this->escapeHtml($task->getTaskTitle()); ?></h3>
<a class="btn btn-default" href="<?php echo $this->url('tasks', ['action' => 'edit', 'task' => $task->getId(), 'project' => $project->getCode()]); ?>"><span class="glyphicon glyphicon-pencil"></span> Edit</a>
<a class="btn btn-default" href="#" data-modal-id="reassign-user-popup" onclick="reassign(); return false;"><span class="glyphicon glyphicon-share-alt"></span> Re-assign</a>


    <div id="reassign-user-popup" class="modal-box">
        <header>
            <a href="#" class="js-modal-close close">x</a>
            <h3>Assign another user</h3>
        </header>
        <div class="modal-body" id="reassign-modal-popup-body">
        </div>
        <footer><a href="#" class="btn btn-default"  onclick="reassignPost(<?= $task->getId(); ?>); return false;"><span class="glyphicon glyphicon-check"></span> Assign</a></footer>
    </div>


<div class="general-info-wrapper">
    <dl class="general-info-attribute-block">
        <dt>Priority:</dt>
        <dd><?= $this->escapeHtml($task->getPriority()) ?></dd>
    </dl>
    <dl class="general-info-attribute-block">
        <dt>Status:</dt>
        <dd><?= $status ?></dd>
    </dl>
    <dl class="general-info-attribute-block">
        <dt>Created Date:</dt>
        <dd><?= date('d F Y', strtotime($task->getDateCreated())) ?></dd>
    </dl>
    <dl class="general-info-attribute-block">
        <dt>Assigned User:</dt>
        <dd><?= $this->escapeHtml($task->getAssignedUser()->getFullName()); ?></dd>
    </dl>
</div>


<div class="description-wrapper">
    <div class="description-label"><strong>Description:</strong></div>
    <div class="description-text"><?= $this->escapeHtml($task->getDescription()) ?></div>
</div>


<?php if($comments): ?>
    <div class="comments-wrapper" id="comments-wrapper">
        <div class="comments-title"><strong>Comments:</strong></div>
        <?php foreach ($comments as $comment): ?>
            <?= $this->partial('comment.phtml', array('comment' => $comment)); ?>
        <?php endforeach; ?>
    </div>
<?php else: ?>
    There are no comments yet
<?php endif; ?>

<div class="add-comment-block">
<!--    --><?//= $commentForm; ?>
    <div class="comment-text">
        <?= $this->formElement($commentForm->get('comment_text')); ?>
    </div>
    <div class="clearer"></div>
    <?= $this->formElement($commentForm->get('submit')); ?>
</div>

<script type="text/javascript">
    function addComment(){
        var data = {};
        data.comment_text = $('#comment-text').val();
        $.ajax({
            type:'POST',
            dataType: 'json',
            url:'/comments/add/<?php echo $task->getId(); ?>',
            data: data,
            success: function(data){
                console.log(data);
                if(data.response) {
                    addMessage(data.message, 'success');
                    $('#comment-text').val('');
                }else{
                    addMessage(data.message, 'danger')
                }
                if(data.html){
                    $(".comments-wrapper").append(data.html);
                }
            }
        });
    }

    function editComment(commentId){
        var commentText = $('#comment-text-' + commentId);
        var editButton = $('#edit-button-' + commentId);
        var commentTextArea = $('#comment-textarea-' + commentId);
        var cancelButton = $('#cancel-edit-button-' + commentId);
        var saveButton = $('#comment-save-button-' + commentId);
        commentText.hide();
        commentTextArea.show();
        cancelButton.show();
        editButton.hide();
        saveButton.show();
    }
    function cancelEditComment(commentId){
        var commentText = $('#comment-text-' + commentId);
        var editButton = $('#edit-button-' + commentId);
        var commentTextArea = $('#comment-textarea-' + commentId);
        var cancelButton = $('#cancel-edit-button-' + commentId);
        var saveButton = $('#comment-save-button-' + commentId);
        commentText.show();
        commentTextArea.hide();
        cancelButton.hide();
        editButton.show();
        saveButton.hide();
    }

    function editCommentPost(commentId){
        var data = {};
        data.comment_text = $('#comment-textarea-' + commentId).val();
        $.ajax({
            type:'POST',
            dataType: 'json',
            url:'/comments/edit/' + commentId,
            data: data,
            success: function(data){
                console.log(data);
                if(data.response) {
                    addMessage(data.message, 'success');
                    cancelEditComment(commentId);
                }else{
                    addMessage(data.message, 'danger')
                }
                if(data.html){
                    $("#comment-block-" + commentId).replaceWith(data.html);
                }
            }
        });
    }

    function reassign(){
        var data = {};
        $.ajax({
            type:'GET',
            dataType: 'json',
            url:'/tasks/reassign',
            data: data,
            success: function(data){
                console.log(data);
                if(data.response) {
//                    addMessage(data.message, 'success');
                }else{
                    addMessage(data.message, 'danger')
                }
                if(data.html){
                    $("#reassign-modal-popup-body").append(data.html);
                }
            }
        });
    }

    function reassignPost(taskId){
        var data = {};
        var data.task_id = taskId;
        $.ajax({
            type:'GET',
            dataType: 'json',
            url:'/tasks/reassign',
            data: data,
            success: function(data){
                console.log(data);
                if(data.response) {
//                    addMessage(data.message, 'success');
                }else{
                    addMessage(data.message, 'danger')
                }
                $("#reassign-modal-popup-body").html('');
            }
        });
    }


    /**
     * jQuery popup js logic
     */
    $(function(){
        var appendthis =  ("<div class='modal-overlay js-modal-close'></div>");

        $('a[data-modal-id]').click(function(e) {
            e.preventDefault();
            $("body").append(appendthis);
            $(".modal-overlay").fadeTo(500, 0.7);
            //$(".js-modalbox").fadeIn(500);
            var modalBox = $(this).attr('data-modal-id');
            $('#'+modalBox).fadeIn($(this).data());
        });


        $(".js-modal-close, .modal-overlay").click(function() {
            $(".modal-box, .modal-overlay").fadeOut(500, function() {
                $(".modal-overlay").remove();
            });
        });

        $(window).resize(function() {
            $(".modal-box").css({
                top: ($(window).height() - $(".modal-box").outerHeight()) / 2,
                left: ($(window).width() - $(".modal-box").outerWidth()) / 2
            });
        });

        $(window).resize();

    });


</script>

</div>

<div class="col-md-3">
    <?php if($estimate != null): ?>
        <!-- Estimate line -->
        <dl class="left-attribute-block">
            <dt>Estimate:</dt>
            <dd><?= $task->getEstimate() ?></dd>
        </dl>
        <div class="progress progress-estimate">
            <div class="progress-bar" role="progressbar" aria-valuenow="<?= $task->getEstimate() ?>"
                 aria-valuemin="0" aria-valuemax="<?= $task->getEstimate() ?>" style="width:100%">
            </div>
        </div>

        <!-- Spent time line -->
        <?php $percentValue = $spentTime * 100 / $estimate; ?>
        <?php $class = ($spentTime > $estimate)? 'progress-bar-danger': 'progress-bar-success'; ?>
        <dl class="left-attribute-block">
            <dt>Spent time:</dt>
            <dd><?= $spentTime ?></dd>
        </dl>
        <div class="progress progress-estimate">
            <div class="progress-bar <?= $class; ?>" role="progressbar" aria-valuenow="<?= $spentTime; ?>"
                 aria-valuemin="0" aria-valuemax="<?= $estimate ?>" style="width:<?= $percentValue; ?>%">
            </div>
        </div>
    <?php endif; ?>
</div>