<?php
$this->headTitle('Users Statistic');

$this->mainMenu()->setActiveItemId('stats');

$this->pageBreadcrumbs()->setItems([
    'Home'=>$this->url('home'),
    'Users Statistic'=>$this->url('stats'),
]);
?>

<h1>Users Statistic</h1>

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

<div id="tabs">
    <ul>
        <?php foreach ($roles as $role): ?>
            <?php if(in_array($role->getName(), $excludedRoles)): ?>
                <?php continue; ?>
            <?php endif; ?>
            <li><a href="#tabs-<?php echo $role->getId(); ?>"><?php echo $role->getName(); ?></a></li>
        <?php endforeach; ?>
    </ul>
    <?php foreach ($roles as $role): ?>
        <?php if(in_array($role->getName(), $excludedRoles)): ?>
            <?php continue; ?>
        <?php endif; ?>
    <?php if(isset($statistic[$role->getId()])): ?>

        <?php $roleUsers = $role->getUsers(); ?>
        <?php $roleUsers->initialize(); ?>
        <?php if(count($roleUsers) == 0): ?>
            <?php continue; ?>
        <?php endif; ?>

        <?php $minorDataExists = false; ?>
        <?php $minorData = false; ?>
        <?php if(isset($statistic[$role->getId()][\Project\Entity\Task::PRIORITY_MINOR])): ?>
            <?php $minorData = $statistic[$role->getId()][\Project\Entity\Task::PRIORITY_MINOR]; ?>
        <?php endif; ?>
        <?php if(is_array($minorData)): ?>
            <?php $minorDataExists = true; ?>
            <?php $header = [['User', 'Estimated Value', 'Actual Value']]; ?>
            <?php $minorData = array_merge($header, $minorData); ?>
        <?php endif; ?>

        <?php $criticalDataExists = false; ?>
        <?php $criticalData = false; ?>
        <?php if(isset($statistic[$role->getId()][\Project\Entity\Task::PRIORITY_CRITICAL])): ?>
            <?php $criticalData = $statistic[$role->getId()][\Project\Entity\Task::PRIORITY_CRITICAL]; ?>
        <?php endif; ?>
        <?php if(is_array($criticalData)): ?>
            <?php $criticalDataExists = true; ?>
            <?php $header = [['User', 'Estimated Value', 'Actual Value']]; ?>
            <?php $criticalData = array_merge($header, $criticalData); ?>
        <?php endif; ?>

    <div id="tabs-<?php echo $role->getId(); ?>">
        <script type="text/javascript">
            google.charts.load('current', {'packages':['bar']});
            <?php if($minorDataExists): ?>
                google.charts.setOnLoadCallback(drawMinorChart<?php echo $role->getId(); ?>);

                function drawMinorChart<?php echo $role->getId(); ?>() {
                    var data = google.visualization.arrayToDataTable(<?php echo json_encode($minorData); ?>);

                    var options = {
                        chart: {
                            title: 'Users performance coefficient for minor tasks',
    //                        subtitle: 'Sales, Expenses, and Profit: 2014-2017',
                        },
                        bars: 'horizontal' // Required for Material Bar Charts.
                    };

                    var chart = new google.charts.Bar(document.getElementById('barchart_material_minor_<?php echo $role->getId(); ?>'));

                    chart.draw(data, google.charts.Bar.convertOptions(options));
                }
            <?php endif; ?>
            <?php if($criticalDataExists): ?>
                google.charts.setOnLoadCallback(drawCriticalChart<?php echo $role->getId(); ?>);
                function drawCriticalChart<?php echo $role->getId(); ?>() {
                    var data = google.visualization.arrayToDataTable(<?php echo json_encode($criticalData); ?>);

                    var options = {
                        chart: {
                            title: 'Users performance coefficient for critical tasks',
    //                        subtitle: 'Sales, Expenses, and Profit: 2014-2017',
                        },
                        bars: 'horizontal' // Required for Material Bar Charts.
                    };

                    var chart = new google.charts.Bar(document.getElementById('barchart_material_critical_<?php echo $role->getId(); ?>'));

                    chart.draw(data, google.charts.Bar.convertOptions(options));
                }
            <?php endif; ?>
        </script>

        <div class="chart-wrapper" id="barchart_material_minor_<?php echo $role->getId(); ?>" style="width: 900px; height: 500px;"></div>
        <div class="chart-wrapper" id="barchart_material_critical_<?php echo $role->getId(); ?>" style="width: 900px; height: 500px;"></div>
    </div>

        <?php endif; ?>
    <?php endforeach; ?>
</div>

<script type="text/javascript">
    document.addEventListener("DOMContentLoaded", function(event) {
        $(function () {
            $("#tabs").tabs();
        });
    });
</script>