<?php

$title = 'My Test Entities';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?php echo $this->url('test', ['action' => 'add']) ?>">Add new test entity</a>
</p>

<table class="table">
    <tr>
        <th>Title</th>
        <th>Artist</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($tests as $test) : ?>
        <tr>
            <td><?= $this->escapeHtml($test->id) ?></td>
            <td><?= $this->escapeHtml($test->name) ?></td>
            <td>
                <a href="<?php echo  $this->url('test', ['action' => 'edit', 'id' => $test->id]) ?>">Edit</a>
                <a href="<?php echo $this->url('test', ['action' => 'delete', 'id' => $test->id]) ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>