<?php

$this->headTitle('View Status');

$this->mainMenu()->setActiveItemId('tasks_menu');

$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Manage Task Statuses' => $this->url('statuses'),
    'View Status' => $this->url('tasks', ['action' => 'view', 'id' => $status->getId()])
]);
?>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<h1>View Project</h1>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
            <tr>
                <th>ID:</th>
                <td>
                <?= $this->escapeHtml($status->getId()) ?></th>
            </tr>
            <tr>
                <th>Label:</th>
                <td>
                <?= $this->escapeHtml($status->getLabel()) ?></th>
            </tr>
        </table>
    </div>
</div>