<?php

$this->headTitle('Add Project');

$this->mainMenu()->setActiveItemId('projects');

$this->pageBreadcrumbs()->setItems([
    'Home'=>$this->url('home'),
    'Manage Projects'=>$this->url('projects'),
    'Add Project'=>$this->url('projects', ['action'=>'add'])
]);

$form->get('code')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Project code'
]);

$form->get('name')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Project name'
]);

$form->get('description')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Description'
]);

$form->get('status')->setAttributes([
    'class'=>'form-control'
]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);

$form->prepare();
?>

<h1>Add Project</h1>

<p>
    Please fill out the following form and click the <i>Create</i> button.
</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('code')); ?>
            <?= $this->formElement($form->get('code')); ?>
            <?= $this->formElementErrors($form->get('code')); ?>
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('name')); ?>
            <?= $this->formElement($form->get('name')); ?>
            <?= $this->formElementErrors($form->get('name')); ?>
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('description')); ?>
            <?= $this->formElement($form->get('description')); ?>
            <?= $this->formElementErrors($form->get('description')); ?>
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('status')); ?>
            <?= $this->formElement($form->get('status')); ?>
            <?= $this->formElementErrors($form->get('status')); ?>                  
        </div>
        
        <?= $this->formElement($form->get('submit')); ?>
        
        <?= $this->form()->closeTag(); ?>
    </div>    
</div>   

