<?php

$this->headTitle('Assign users to the project');

$this->mainMenu()->setActiveItemId('roles');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'Manage Roles'=>$this->url('roles'),
            'Edit Role'=>$this->url('roles', ['action' => 'edit', 'id' => $project->getId()])
            ]);

$form->get('submit')
        ->setAttributes(['class'=>'btn btn-primary'])
        ->setValue('Save');

$form->prepare();
?>

<h1>Assign users for "<?= $this->escapeHtml($project->getName()) ?>" project</h1>



<div class="row">
    <div class="col-md-8">
        <?= $this->form()->openTag($form); ?>
        <table class="table table-striped table-bordered">
            <tr>
                <th>Name</th>
                <th>Email</th>
                <? /*todo: add user role */ ?>
            </tr>
            <?php foreach ($allUsers as $user):
                $element = $form->get('users')->get($user->getId());
            ?>
            <tr>
                <td>
                    <div class="checkbox">
                        <label><input type="checkbox" name="<?= $this->escapeHtmlAttr($element->getName()) ?>"
                                      value="<?= $this->escapeHtmlAttr($element->getCheckedValue()) ?>"
                                      <?php if ($element->isChecked()) echo 'checked'?>
                                      <?php if ($element->getAttribute('checked')) echo 'checked="checked"'?>>
                            <?= $this->escapeHtml($element->getLabel()) ?>
                        </label>
                        <?= $this->formElementErrors($element); ?>
                    </div>
                </td>
                <td>
                    <?= $this->escapeHtml($user->getEmail()) ?>
                </td>
            </tr>
            <?php endforeach; ?>
        </table>
        <?= $this->formElement($form->get('csrf')); ?>

        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        
        
        
        
        
    </div>    
</div>   



