<?php

$this->headTitle('Scope of Work');

$this->mainMenu()->setActiveItemId('projects');

$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Manage Projects' => $this->url('projects'),
    'Add Project' => $this->url('projects', ['action'=>'add'])
]);

$form->get('description')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Description'
]);

$form->get('deadline_date')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Project name'
]);

$form->get('submit')->setAttributes(['class' => 'btn btn-primary']);

$form->prepare();
?>

<h2>Create Scope of work for <?= $project->getName(); ?></h2>


<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('description')); ?>
            <?= $this->formElement($form->get('description')); ?>
            <?= $this->formElementErrors($form->get('description')); ?>
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('deadline_date')); ?>
            <?= $this->formElement($form->get('deadline_date')); ?>
            <?= $this->formElementErrors($form->get('deadline_date')); ?>
        </div>

        <?= $this->formElement($form->get('submit')); ?>
        
        <?= $this->form()->closeTag(); ?>
    </div>    
</div>   

