<?php

$this->headTitle('Edit Technical assignment');

$this->mainMenu()->setActiveItemId('projects');

$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Manage Projects' => $this->url('projects'),
    'View Project' => $this->url('projects', ['action' => 'view', 'code' => $project->getCode()]),
    'View Technical Assignment' => $this->url('projects', ['action' => 'viewTechnicalAssignment', 'code' => $project->getCode()]),
    'Edit Technical Assignment' => $this->url('projects', ['action' => 'editTechnicalAssignment', 'code' => $project->getCode()])
]);

$form->get('description')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Description'
]);

$form->get('deadline_date')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Deadline Date'
]);

$form->get('submit')
    ->setAttributes(['class' => 'btn btn-primary'])
    ->setValue('Save');

$form->prepare();
?>

<h1>Edit Project <?= $this->escapeHtml($project->getCode()) ?></h1>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('description')); ?>
            <?= $this->formElement($form->get('description')); ?>
            <?= $this->formElementErrors($form->get('description')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('deadline_date')); ?>
            <?= $this->formElement($form->get('deadline_date')); ?>
            <?= $this->formElementErrors($form->get('deadline_date')); ?>
        </div>

        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>   

