<?php

$this->headTitle('Edit Project');

$this->mainMenu()->setActiveItemId('projects');

$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Manage Projects' => $this->url('projects'),
    'Edit Project' => $this->url('projects', ['action' => 'edit', 'id' => $project->getId()])
]);

$form->get('code')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Project Code'
]);

$form->get('name')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Project name'
]);

$form->get('description')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Description'
]);

$form->get('status')->setAttributes([
    'class' => 'form-control'
]);

$form->get('submit')
    ->setAttributes(['class' => 'btn btn-primary'])
    ->setValue('Save');

$form->prepare();
?>

<h1>Edit Project <?= $this->escapeHtml($project->getCode()) ?></h1>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('code')); ?>
            <?= $this->formElement($form->get('code')); ?>
            <?= $this->formElementErrors($form->get('code')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('name')); ?>
            <?= $this->formElement($form->get('name')); ?>
            <?= $this->formElementErrors($form->get('name')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('description')); ?>
            <?= $this->formElement($form->get('description')); ?>
            <?= $this->formElementErrors($form->get('description')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('status')); ?>
            <?= $this->formElement($form->get('status')); ?>
            <?= $this->formElementErrors($form->get('status')); ?>
        </div>

        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>   

