<?php
$this->headTitle('Projects');

$this->mainMenu()->setActiveItemId('projects');

$this->pageBreadcrumbs()->setItems([
    'Home'=>$this->url('home'),
    'Manage Projects'=>$this->url('projects'),
]);
?>

<h1>Manage Projects</h1>

<p>
    <a class="btn btn-default" href="
    <?= $this->url('projects', ['action'=>'add']); ?>">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> New Project
    </a>
</p>

<table class="table table-striped">

    <tr>
        <th>ID</th>
        <th>Code</th>
        <th>Name</th>
        <th>Description</th>
        <th>Date Created</th>
        <th>Actions</th>
    </tr>

    <?php foreach ($projects as $project): ?>

        <tr>
            <td><?= $this->escapeHtml($project->getId()); ?></td>
            <td><?= $this->escapeHtml($project->getCode()); ?></td>
            <td><?= $this->escapeHtml($project->getName()); ?></td>
            <td><?= $this->escapeHtml($project->getDescription()); ?></td>
            <td><?= $this->escapeHtml($project->getDateCreated()); ?></td>
            <td>
                <a class="btn btn-info" href="<?= $this->url('projects',
                    ['action'=>'edit', 'code'=>$project->getCode()]); ?>">
                    <span class="glyphicon glyphicon-pencil" ></span> Edit
                </a>
                <a class="btn btn-info" href="<?= $this->url('projects',
                    ['action'=>'view', 'code'=>$project->getCode()]); ?>">
                    <span class="glyphicon glyphicon-pencil" ></span> View
                </a>
                <?php if ($this->rbacManager->isGranted(null, 'projects.delete')): ?>
                    <a class="btn btn-danger" href="<?= $this->url('projects',
                        ['action' => 'delete', 'code' => $project->getCode()]); ?>">
                        <span class="glyphicon glyphicon-remove"></span> Delete
                    </a>
                <?php endif; ?>
            </td>
        </tr>

    <?php endforeach; ?>

</table>

