<?php
$this->headTitle('View Technical Assignment');

$this->mainMenu()->setActiveItemId('projects');

$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Manage Projects' => $this->url('projects'),
    'View Project' => $this->url('projects', ['action' => 'view', 'code' => $project->getCode()]),
    'View Technical Assignment' => $this->url('projects', ['action' => 'viewTechnicalAssignment', 'code' => $project->getId()])
]);
?>

<div class="col-md-9">


<div class="project-header">
    <h2>Technical Assignment for <?= $project->getName(); ?></h2>
    <a class="btn btn-default" href="#" data-modal-id="attach-file-popup" onclick="return false;"><span class="glyphicon glyphicon-save-file"></span> Attach file</a>

    <a class="edit=link" href="<?= $this->url('projects', ['action' => 'editTechnicalAssignment', 'code' => $project->getCode()]); ?>">Edit</a>
</div>

<div class="general-info-wrapper">
    <dl class="general-info-attribute-block">
        <dt>Deadline Date:</dt>
        <dd><?= date('d F Y', strtotime($technicalAssignment->getDeadlineDate())) ?></dd>
    </dl>
    <dl class="general-info-attribute-block">
        <dt>Created Date:</dt>
        <dd><?= date('d F Y', strtotime($technicalAssignment->getDateCreated())) ?></dd>
    </dl>
    <?php if($technicalAssignment->getDateUpdated()): ?>
        <dl class="general-info-attribute-block">
            <dt>Updated Date:</dt>
            <dd><?= date('d F Y', strtotime($technicalAssignment->getDateUpdated())) ?></dd>
        </dl>
    <?php endif; ?>

</div>


<div class="description-wrapper">
    <div class="description-label"><strong>Description:</strong></div>
    <div class="description-text"><?= $this->escapeHtml($project->getDescription()) ?></div>
</div>


<div class="attachments-wrapper">
    <div class="attachments-label"><strong>Attachments:</strong></div>
    <div class="attachments-items-wrapper">
        <?php foreach($attachments as $attachment): ?>
            <?= $this->partial('attachment.phtml', array('attachment' => $attachment)); ?>
        <?php endforeach; ?>
    </div>
</div>


</div>

<div class="col-md-3">

</div>



<div id="attach-file-popup" class="modal-box">
    <header>
        <a href="#" class="js-modal-close close">x</a>
        <h3>Assign another user</h3>
    </header>
    <div class="modal-body" id="attach-file-popup-body">
        <form name="upload-form" id="upload-form" method="post" enctype="multipart/form-data" action="<?php echo $this->url('system', ['action' => 'uploadFile']); ?>">
            <input type="hidden" name="project_id" value="<?= $project->getId(); ?>">
            <div class="form-element">
                <label for="image-file">File Upload</label>
                <input type="file" name="attachment" id="attachment">
            </div>

            <button class="btn btn-default" style="margin-top: 20px; float: right;;">Submit</button>
            <div class="clearer"></div>
        </form>

    </div>
</div>


<script>

</script>
