<?php
$this->headTitle('View Project');

$this->mainMenu()->setActiveItemId('projects');

$this->pageBreadcrumbs()->setItems([
    'Home'=>$this->url('home'),
    'Manage Projects'=>$this->url('projects'),
    'View Project'=>$this->url('projects', ['action'=>'view', 'id'=>$project->getId()])
]);
?>

<h1>View Project</h1>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
             <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($project->getId()) ?></th>
            </tr>
            <tr>
                <th>Code:</th>
                <td><?= $this->escapeHtml($project->getCode()) ?></th>
            </tr>
            <tr>
                <th>Name:</th>
                <td><?= $this->escapeHtml($project->getName()) ?></th>
            </tr>
            <tr>
                <th>Description:</th>
                <td><?= $this->escapeHtml($project->getDescription()) ?></th>
            </tr>
            <tr>
                <th>Date Created:</th>
                <td><?= $this->escapeHtml($project->getDateCreated()) ?></th>
            </tr>
            <tr>
                <th>Status:</th>
                <td><?= $this->escapeHtml($project->getStatusAsString()) ?></th>
            </tr>
        </table>
    </div>
</div>

<h2>Project tasks:</h2>
<?php if(count($tasks)): ?>
    <?php foreach ($tasks as $task): ?>
        <div class="task-wrapper">
            <div class="task-title"><?= $task->getTaskTitle(); ?></div>
        </div>
    <?php endforeach; ?>
<?php endif; ?>

<button type="button" class="btn btn-default" onclick="addTask()">
    <span class="glyphicon glyphicon-plus"></span> Add Task
</button>

<script type="text/javascript">
    function addTask(project){
        var params = '';
        if(typeof(project) != 'undefined'){
            params = '?project=' + project;
        }
        document.location = '<?= $this->url('tasks', ['action' => 'add', 'id' => $project->getId()]); ?>';
    }
    function addUser(project){
        var params = '';
        if(typeof(project) != 'undefined'){
            params = '?project=' + project;
        }
        document.location = '<?= $this->url('projects', ['action'=>'assignUsers', 'id' => $project->getId()]); ?>';
    }
</script>


<h2>Assigned users:</h2>
<?php if(count($assignedUsers)): ?>
    <?php foreach ($assignedUsers as $user): ?>
        <div class="user-wrapper">
            <div class="user-name"><?= $user->getFullName(); ?></div>
        </div>
    <?php endforeach; ?>
<?php endif; ?>

<button type="button" class="btn btn-default" onclick="addUser(<?= $project->getId(); ?>)">
    <span class="glyphicon glyphicon-plus"></span> Assign Users To Project
</button>

