<?php
$this->headTitle('View Project');

$this->mainMenu()->setActiveItemId('projects');

$this->pageBreadcrumbs()->setItems([
    'Home'=>$this->url('home'),
    'Manage Projects'=>$this->url('projects'),
    'View Project'=>$this->url('projects', ['action'=>'view', 'code' => $project->getCode()])
]);
?>

<div class="col-md-9">


<div class="project-header">
    <h2><?= $project->getName(); ?></h2>
    <a class="edit=link" href="<?= $this->url('projects', ['action' => 'edit', 'code' => $project->getCode()]); ?>">Edit</a>
</div>


<div class="general-info-wrapper general-info-wrapper-3">
    <dl class="general-info-attribute-block">
        <dt>Code:</dt>
        <dd><?= $this->escapeHtml($project->getCode()) ?></dd>
    </dl>
    <dl class="general-info-attribute-block">
        <dt>Status:</dt>
        <dd><?= $this->escapeHtml($project->getStatusAsString()) ?></dd>
    </dl>
    <dl class="general-info-attribute-block">
        <dt>Created Date:</dt>
        <dd><?= date('d F Y', strtotime($project->getDateCreated())) ?></dd>
    </dl>
    <dl class="general-info-attribute-block">
        <dt>Participants:</dt>
        <dd>&nbsp
        <?php $i = 0; ?>
        <?php $participantsCount = count($participants); ?>
        <?php foreach ($participants as $participant): ?>
            <?php $i++; ?>
            <a target="_blank" href="<?= $this->url('users', ['action' => 'view', 'id' => $participant->getId()]); ?>"><?= $participant->getFullName(); ?><?= ($participantsCount != $i)?',':''; ?></a>
        <?php endforeach; ?>
        </dd>
    </dl>
    <?php if($technicalAssignment): ?>
        <dl class="general-info-attribute-block">
            <dt>Deadline Date:</dt>
            <dd><?= date('d F Y', strtotime($technicalAssignment->getDeadlineDate())) ?></dd>
        </dl>
        <dl class="general-info-attribute-block">
            <dt>Technical Assignment:</dt>
            <dd>
                <a href="<?= $this->url('projects', ['action' => 'viewTechnicalAssignment', 'code' => $project->getCode()]); ?>">View</a></dd>
        </dl>
    <?php else: ?>
        <dl class="general-info-attribute-block">
            <dt>Technical Assignment:</dt>
            <dd><a href="<?= $this->url('projects', ['action' => 'createTechnicalAssignment', 'code' => $project->getCode()]); ?>">Create</a></dd>
        </dl>
    <?php endif; ?>
</div>


<div class="block-wrapper">
    <div class="description-label"><strong>Description:</strong></div>
    <div class="description-text"><?= $project->getDescription() ?></div>
</div>


<button type="button" class="btn btn-default" onclick="addTask()">
    <span class="glyphicon glyphicon-plus"></span> Add Task
</button>

<script type="text/javascript">
    function addTask(project){
        var params = '';
        if(typeof(project) != 'undefined'){
            params = '?project=' + project;
        }
        document.location = '<?= $this->url('tasks', ['action' => 'add', 'project' => $project->getCode()]); ?>';
    }
    function assignUsers(project){
        var params = '';
        if(typeof(project) != 'undefined'){
            params = '?project=' + project;
        }
        document.location = '<?= $this->url('projects', ['action' => 'assignUsers', 'code' => $project->getCode()]); ?>';
    }
</script>

<button type="button" class="btn btn-default" onclick="assignUsers(<?= $project->getId(); ?>)">
    <span class="glyphicon glyphicon-plus"></span><span class="glyphicon glyphicon-user"></span> Assign Users To Project
</button>

</div>

<div class="col-md-3">
    <h2>Tasks:</h2>
    <div class="form-group">
        <label for="status_filter">Status Filter</label>
        <select name="status_filter" id="status_filter" class="form-control">
            <?php foreach ($allStatuses as $status): ?>
                <option value="<?= $status->getId(); ?>" <?php echo ($currentFilterStatus == $status->getId())? 'selected="selected"':'';?> ><?= $status->getLabel(); ?></option>
            <?php endforeach; ?>
        </select>
    </div>
    <?php if(count($tasks)): ?>
        <?php foreach ($tasks as $task): ?>
            <div class="task-wrapper">
                <a href="<?= $this->url('tasks', ['action' => 'view', 'project' => $project->getCode(), 'task' => $task->getId()]); ?>"><?= $task->getId(); ?>: <?= $task->getTaskTitle(); ?></a>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>

    <script type="text/javascript">
        $("#status_filter" ).change(function(element) {
            console.log($(this));
            console.log($(this).val());
            var selectedStatus = $(this).val();
            var generalUrl = '<?= $this->url('projects', ['action'=>'view', 'code' => $project->getCode()]); ?>';
            window.location = generalUrl + '?filter_status='+selectedStatus
        });
    </script>
</div>