<?php
$this->headTitle('About');

$this->mainMenu()->setActiveItemId('about');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'About'=>$this->url('about'),
            ]);
?>

<h1>About</h1>

<p>
    Application name: Projects management system
</p>

<p>
    Application description: This is the application powered by Zend Framework 3. It helps IT business to manage projects, users, tasks etc.
    The key feature of the system is auto users assignment to projects based on previous experience.
</p>
