<?php
$this->headTitle('Welcome');

$this->mainMenu()->setActiveItemId('home');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home')
            ]);
?>

<h1>Welcome to the project management system</h1>

<p>
    This is the application powered by Zend Framework 3. It helps IT business to manage projects, users, tasks etc.
    The key feature of the system is auto users assignment to projects based on previous experience.
</p>

<p>You can find this application guide here</p>

<p>
    Click the <em>Sign in</em> button at the top right. This is train application so to sign in, just use the
    following credentials:
    <ul>
        <li>Username: <em>admin@example.com</em></li>
        <li>Password: <em>Secur1ty</em></li>
    </ul>

</p>



